### ISSUE TITLE
Clean __init__.py

### ISSUE THREAD

**Issue by jorgefandinno** [jorgefandinno/eclingo#2]
Imports should be removed from all __init__.py and moved in the necessary files.

For instance:

https://github.com/jorgefandinno/eclingo/blob/1dfc77dac16bc4acd212afae60cc318738b947f6/eclingo/__init__.py#L1-L2

**Comment by lute47lillo** [comment]
Is this issue solved? Or do we want to get rid of the __init__.py files to create our own namespace packages?

**Comment by jorgefandinno** [comment]
> Is this issue solved? Or do we want to get rid of the **init**.py files to create our own namespace packages?

You are right, it is solved.
