### ISSUE TITLE
src/eclingo/internal_states/__init__.py

### ISSUE THREAD

**Issue by jorgefandinno** [jorgefandinno/eclingo#22]
Remove all content from this file.

Imports in other files may need to be added.
Those imports should be some of the imports removed from this file.

**Comment by lute47lillo** [comment]
I've opened a pull request for this issue.

On the other hand, I have been getting some Session typecheked failed from running nox.
<img width="1117" alt="Screen Shot 2022-06-23 at 5 31 09 PM" src="https://user-images.githubusercontent.com/65786380/175425823-874f10b5-0d31-46b0-aed7-7c22596c2b1b.png">

Do you know what it might be?

**Comment by lute47lillo** [comment]
Yes, I solved it. You can close this issue too.
