### ISSUE TITLE
Create a version using reification

### ISSUE THREAD

**Issue by jorgefandinno** [jorgefandinno/eclingo#5]
NOT TO BE ADDRESSED YET

eclingo creates two programs that it feeds to clingo both for guessing candidates and testing them. This is done in fully python. The idea is that now python does only the minimum necessary so we can create those programs in ASP itself. This way will be faster to implement new ideas.

The first step is change the way we encode non-epistemic literals.

For instance, the following test

https://github.com/jorgefandinno/eclingo/blob/93554201963ad20dc242c841af32759236c93713/tests/test_parsing.py#L85

with reification would look something like

```python
self.assert_equal_program(parse_program(":- &k{a}."), ":- k(a). {k_u(a)} :- u(a).")
```

The final objective is to get something like

```python
self.assert_equal_program(parse_program(":- &k{a}."), ":- k(a). {k(a)} :- u(a).")
```

but we will address this later.

---

### Further notes

This may seem a very small change, but crucial. In ASP we cannot inspect if the name

In the first step, we need to change the way we encode epistemic literals. For instance, the following test

https://github.com/jorgefandinno/eclingo/blob/93554201963ad20dc242c841af32759236c93713/tests/test_parsing.py#L85

with reification would look something like

```python
self.assert_equal_program(parse_program(":- &k{a}."), ":- k(a). {k(a)} :- u(a).")
```

This may seem a very small change, but crucial. In ASP we cannot inspect if the name of a predicate starts with ```k_``` or ```u_``` but we can access the whole name. By writing ```k(a)``` and ```u(a)``` instead of ```k_u_a``` and ```u_a``` we can know in ASP if a literal represents and subjective literal ```k(a)``` or an objective literal ```u(a)```.  We will later use this to create the program in ASP using metaprogramming.

As an example, suppose that we want to and a rule of the form ```{k(a)} :- u(a).``` for every atom ```a``` in the program (there is something like this currently in ```eclingo```). Right now, the python code must inspect the program, built a rule of this form for each atom and add it to the program using clingo api. Using reification, we obtain the same behaviour by adding rule
```
{k(A)} :- u(A).
```
in the ASP program.

At least part of this first step can be accomplished using the following function

https://potassco.org/clingo/python-api/5.5/clingox/ast.html#clingox.ast.reify_symbolic_atoms

**Comment by jorgefandinno** [comment]
NOT TO BE ADDRESSED YET

**Comment by lute47lillo** [comment]
I've been reading the following paper: https://arxiv.org/pdf/2008.06692.pdf sections on Meta-programming that you sent me just to get a better picture of reification.

Is this new version of trying to implement reification for subjective literals? I see that clingo already has reification, so I guess this issue is to address the extension of a reify version, right?

**Comment by jorgefandinno** [comment]
eclingo creates two programs that feeds ti clingo both guessing candidates and testing them. This is done in python. The idea is that now python does only the minimum necessary so we can create those programs in ASP itself. This way will be faster to implement new ideas.

**Comment by lute47lillo** [comment]
Closing issue. Refer to pull request #47 as to latest changes introducing reification.
