### ISSUE TITLE
Checking for arguments of literals when building World Views.

### ISSUE THREAD

**Issue by lute47lillo** [jorgefandinno/eclingo#54]
While cleaning up and modifying existing tests to make use of the reification version I encountered certain programs such as:

**a(1). b :- &k{a(X)}.**

which world view using the non-reification version of eclingo yield:

**[["&k{a(1)}"]]**

However, using the newly included reification version only yields:

[["&k{a}"]]

without the Number Symbol argument 1. That is why, I have implemented on #53 a check snippet function that checks for possible arguments and includes them while constructing the World View. 
https://github.com/jorgefandinno/eclingo/blob/f38cf46f30bef4f518d142a3279cb2af3ed7c7cf/src/eclingo/solver/world_view_builder.py#L137-L141

Do we want to include those arguments, or should not be included?
@jorgefandinno

**Comment by jorgefandinno** [comment]
Why can you replace this code
```
        # Check for explicit negation
        is_explicit = literal_symbol.positive

        arguments: Sequence[Symbol] = []
        if literal_symbol.arguments:
            for args in literal_symbol.arguments:
                arguments.append(args)

        new_symbol = Function(literal_symbol.name, [], is_explicit)
        literal = Literal(new_symbol, sign)

        return EpistemicLiteral(literal, Sign.NoSign, True)
```
just with
```
return EpistemicLiteral(literal_symbol, Sign.NoSign, True)
```?

**Comment by lute47lillo** [comment]
#53 -> Fixes it based on comment by @jorgefandinno.
