### ISSUE TITLE
--output-e=rewritten

### ISSUE THREAD

**Issue by jorgefandinno** [jorgefandinno/eclingo#60]
Be sure to complete #59 before addressing this issue.

Add a ```--output-e=rewritten``` new option for the command line.
If we un ```eclingo --output-e=rewritten program.lp```, it should it should print the rewritten program an exist.

Example:
```bash
echo "a. b :- &k{a}." | eclingo --output-e=rewritten
u(a).
u(b) :- k(u(a)).
{ k(u(a)) } :- u(a).
```

We cannot modify the options of ```--output``` so we need to add ```--ouput-e```.

**Comment by lute47lillo** [comment]
Addressed issue on last merge.
