### ISSUE TITLE
Clingoext SymbolicBackend 

### ISSUE THREAD

**Issue by jorgefandinno** [jorgefandinno/eclingo#9]
clingoext  SymbolicBackend can be replaced by their clingox counterpart.

Some occurrences have been removed. Remove the remaining. We can replace

```with SymbolicBackend(clingoext.symbolic_backend()) as backend:```

by

```with SymbolicBackend(control_test.control.backend()) as backend:```

After all occurrences have been replaced we can remove it from clingoext.

https://github.com/jorgefandinno/eclingo/blob/4c610d272584d0981e4af7c33299563ffc37bdb7/eclingo/util/clingoext.py#L101

**Comment by lute47lillo** [comment]
Is the idea to remove the symbolic_backend references to the function symbolic_backend in the Class Control of file clingoext.py for the function backend on that same class Control?

https://github.com/jorgefandinno/eclingo/blob/5828d949d767345a327646c6c40da0d88316362f/eclingo/util/clingoext.py#L101-L105

**Comment by jorgefandinno** [comment]
> Is the idea to remove the symbolic_backend references to the function symbolic_backend in the Class Control of file clingoext.py for the function backend on that same class Control?
> 
> https://github.com/jorgefandinno/eclingo/blob/5828d949d767345a327646c6c40da0d88316362f/eclingo/util/clingoext.py#L101-L105

Yes, but there is some subtle difference. In line 102 ```SymbolicBackend``` refers to a class in clingoext.py. The final result should refer to ```clingox.backend.SymbolicBackend```

https://potassco.org/clingo/python-api/5.5/clingox/backend.html#clingox.backend.SymbolicBackend

However, now that you mention this, it may be easier to replace in 102 ```SymbolicBackend```  with ```clingox.backend.SymbolicBackend```. If this work, the replacement afterwards is trivial.

**Comment by lute47lillo** [comment]
Yes, so that actually works and passes all tests. Changing line 102 for:
return clingox.backend.SymbolicBackend(self.control.backend())

Now, is the Class SymbolicBackend going to be necessary, or that is the one that will be substitute by the clingox counterpart?

**Comment by jorgefandinno** [comment]
Check that it is not used anywhere else. If so, you can remove it.

**Comment by lute47lillo** [comment]
Changes from jorge/typing are pulled and merged into lute/SymbolicBackendFix. All the tests have passed and is ready for merge after review.
